### ISSUE TITLE
Unable to convert heic to jpg taken by iPhone 15 pro iOS18

### ISSUE THREAD

**Issue by tza17313** [strukturag/libheif#1190]
I found that the heic format photos taken by **iPhone15 pro** under **iOS18** cannot be converted to jpg by **heif-convert**

libheif version: 1.17.6

Here are some logs：
```bash
nero@d2c24395c402:/upload# heif-convert IMG_1159.HEIC 1.jpg
Could not read HEIF/AVIF file: Invalid input: Unspecified: Too many auxiliary image references

nero@d2c24395c402:/upload# heif-info IMG_1159.HEIC
MIME type: image/heic
main brand: heic
compatible brands: tmap, heic, mif1
Could not read HEIF/AVIF file: Invalid input: Unspecified: Too many auxiliary image references
```

When the iPhone 15 Pro system is still iOS17, the HEIC photos taken can be converted to JPG using the above command.

The file can be downloaded via the link below：

[IMG_1159.zip](https://github.com/user-attachments/files/15864812/IMG_1159.zip)

https://drive.google.com/file/d/1kEBvALrnM0EUwkQzsg8YL0Pwd8ZpRWWO/view?usp=sharing

**Comment by bradh** [comment]
Can you try with this branch: https://github.com/strukturag/libheif/tree/develop-v1.18.0 ?

I think I have that resolved by https://github.com/strukturag/libheif/commit/58ba30df608e540bfd0f4e5642ba79ba0dfd7628

**Comment by farindk** [comment]
With `develop-v1.18.0`, I get: 
````
Could not read HEIF/AVIF file: Invalid input: Non-existing item ID referenced: Non-existing aux image referenced
````
Maybe the problem is that the shared aux image is a `tmap` image.

**Comment by fxthomas** [comment]
For reference: the `tmap` image is a derived image (more info about that HEIF feature [here](https://nokiatech.github.io/heif/technical.html)) that implements the upcoming [ISO/CD 21496-1](https://www.iso.org/standard/86775.html) standard which is meant to replace all the current incompatible/proprietary HDR gain map implementations.

It sounds like it's ignored by `m_all_images` in `libheif/context.cc` because the derived image type is not yet supported, but some other items reference it and make parsing fail.

I used GPAC/mp4box on one of the samples I have and I think at least the EXIF block reference both the primary image and the `tmap` -- I could be wrong, the structure is difficult to parse as I'm not used to it.

**Comment by farindk** [comment]
Yes, we even have a pull request to add `tmap` support, but I didn't integrate it yet as nothing about the standard is public yet. Or I didn't find it. Adobe has removed all specific information from their website.

On the other hand, we should probably ignore all references that we cannot parse because there might be other extensions in the future that give rise to the same issue.

**Comment by farindk** [comment]
Fixes this. Gain map is not read yet.

**Comment by coltography** [comment]
Any update on this?

**Comment by Ashok-Varma** [comment]
hi @farindk will this be added in next release cut?
any rough estimates on the next release cut?

**Comment by luohuide** [comment]
Please release it as soon as possible, IOS 18 photos require it.

**Comment by lastzero** [comment]
@farindk Awesome, thanks a lot! I've tested `heif-dec` in version 1.18.1 (presumably the same as `heif-convert` in earlier versions), however the image orientation now seems to be wrong even for images taken with an iPhone 15 Pro that has iOS 17 installed:

- https://github.com/photoprism/photoprism/issues/4439#issuecomment-2265616780

Based on previous feedback, the orientation issues we observed earlier were supposed to be caused by a bug in an old iOS version well before iOS 17 - so this is unexpected:

- https://github.com/strukturag/libheif/issues/227#issuecomment-1554505667

It seems possible that `libheif` itself is working properly and the issue is instead caused by `heif-dec`, e.g. because it copies the metadata 1:1 without changing the Exif `Orientation` value, even though the image is already rotated?

If so, should using `libheif` through `libvips` solve this? The only downside would be losing compatibility with Linux < 3.17 and 32-bit operating systems, as `libvips` is not compatible with these:

- https://github.com/photoprism/photoprism/issues/4339
- https://github.com/photoprism/photoprism/issues/4299

**We would be very grateful for any advice on how we can solve the HEIC orientation issues for our users!** :pray:

**Comment by lastzero** [comment]
> It seems possible that `libheif` itself is working properly and the issue is instead caused by `heif-dec`, e.g. because it copies the metadata 1:1 without changing the Exif `Orientation` value, even though the image is already rotated?

Note that I was able to fix the JPEG image orientation by simply setting the value of the Exif Orientation tag to 1 after new files have been generated with `heif-dec`. Since the behavior was different with the `heif-convert` command included in v1.17.1, we added a new config option to our software that allows users of older versions to change this. This is not ideal, but a workable solution.

Based on my tests, there is still one HEIC image file where the generated JPEG has an incorrect orientation. However, since it is from an iPhone 7 and the camera software is displayed as "ProCam 10.5.8", I believe it is not a problem with `libheif` but with the file itself:

- https://dl.photoprism.app/samples/Formats/Image/HEIC/iphone_7.heic

Hopefully this information will help other developers who come across the same issue! :hugs:

**Comment by farindk** [comment]
Issue might be fixed with e7c564996b9174e4362b9952b59c535bdb549d89.

What happened: `heif-dec` (or `heif-convert`) should reset the Exif orientation tag to "normal" when converting to JPEG. However, we added a bounds check to avoid the reader accessing memory beyond the Exif block in case the data is faulty. Unfortunately, the check was in the wrong direction such that it did not read the Exif block completely and thus did not reset the orientation tag. (I.e. what you have now done manually.)

I'll release an updated v1.18.2 in the coming days.
Maybe you can check that it works again in the `v1.18.x` branch.

BTW: I also noticed that there are some image width/height fields in the Exif that should also be swapped for rotated images. I've added that too.

PS: thanks for your support.

**Comment by lastzero** [comment]
I'm glad my report helped find and fix this issue! I can confirm that it also occurred with v1.17.6, which I believe is the version containing the vulnerability fix:
- https://dl.photoprism.app/dist/libheif/

Setting width and height based on the actual JPEG dimensions is also a welcome improvement. From what I remember, we worked around that by getting width and height from the JPEG file headers rather than trusting the Exif metadata.

I am traveling until August 19 and will therefore not be able to test the changes right now. However, I trust your own testing, so please feel free to go ahead and release these improvements as a new version! 👍

**Comment by birdman002** [comment]
Is there any chance or getting this fix applied to older versions this package?

**Comment by farindk** [comment]
> Is there any chance of getting this fix applied to older versions this package?

What would be the difference to simply install a v1.18.x or v1.19.x version?

**Comment by birdman002** [comment]
> > Is there any chance of getting this fix applied to older versions this package?
> 
> What would be the difference to simply install a v1.18.x or v1.19.x version?

Due to circumstances of having to stay on a certain version of alpine we can't do 1.18 or 1.19. We may have to manually download and install this package but curious if there is any plans to fix previous versions say 1.16 or 1.17

**Comment by farindk** [comment]
I didn't plan this because I don't see a reason to release another v1.17.x version when v1.18.2 would do the same and it's also backwards compatible.

If you really want to stay with the v1.17.x, you can cherry pick 4d76bae for the fix.

**Comment by SeDi343** [comment]
Can this be updated also on launchpad for Ubuntu 24.04 LTS? The latest one for [The Noble Numbat](https://launchpad.net/ubuntu/noble/+source/libheif) is 1.17.6-1ubuntu4.1.

**Comment by fancycode** [comment]
Feel free to use our PPA to get packages of more recent versions than what Canonical provides in the official repositories.

https://launchpad.net/~strukturag/+archive/ubuntu/libheif

**Comment by abhchand** [comment]
@fancycode - any idea why the latest version is not found in that PPA? 

```shell
$ sudo add-apt-repository ppa:strukturag/libheif
$ sudo apt update
$ sudo apt install libheif

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libheif
```

Thanks for all your work here - much appreciated 🙏🏾

**Comment by steve-o** [comment]
Of note `ffmpeg` recently pushed support for HEIC and HEIF files that break with `libheif`.

https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/5ff8395e7806ad27743829b047067098c288782a
