### ISSUE TITLE
ppa builds for Ubuntu noble 24.04

### ISSUE THREAD

**Issue by ttk** [strukturag/libheif#1225]
I noticed that ppa builds are missing for Ubuntu 24.04.  Any chance they can be added?  24.04 is a LTS release.

**Comment by jerbob92** [comment]
I have made a repository to do some automated builds for Ubuntu 20.04, 22.04 and 24.04, due to the lack of PPA updates, you can find it here:
https://github.com/jerbob92/libheif-packaging

A deb file can be downloaded in the release.

Please note that it's not the same as the packages in the PPA, it doesn't contain all plugins and it's not separated out per component.

I also noticed that in 24.04, `ubuntu-desktop` depends on libheif packages from the default repositories, this deb file conflicts with those packages so you can't install this without removing ubuntu-desktop. Don't have a solution for that yet, but if you want to use it in a docker or server install it should be fine!

**Comment by jerbob92** [comment]
@farindk thanks! Have corrected the readme!

**Comment by technicalpickles** [comment]
What is involved with updating the PPA? It sounds like it is manual and I'm wondering if there.

**Comment by fancycode** [comment]
Our PPA will be updated with 1.19.1 shortly, this will include a build for Ubuntu Noble (24.04).
