### ISSUE TITLE
libheif-1.8.0: create_symlink tries to directly modify real file system instead of building dir

### ISSUE THREAD

**Issue by pacho2** [strukturag/libheif#1249]
Hello,

Since the update to 1.18.0 we are having an issue to package it on Gentoo. We build the packages on a build directory and, once everything is installed there, we proceed to effectively moving everything under the real file system (controlled by our package manager). 

With the new 1.18.0 version, it seems that cmake tries to directly modify the real filesystem. As a consequence, our sandbox system blocks the create_symlink call and causes the build to fail:
https://github.com/gentoo/gentoo/pull/36951#issuecomment-2237372033

Supposedly, this could be fixed making create_symlink to honor the DESTDIR variable (as all the other install scripts are doing), but I am not familiar enough with cmake to modify it :S
https://github.com/strukturag/libheif/blob/master/examples/CMakeLists.txt#L37

Thanks for your help

**Comment by farindk** [comment]
Would it work if we prepend `DESTDIR` to the two directory paths? I.e. using `${DESTDIR}${CMAKE_INSTALL_PREFIX}/...` at the two places in that CMakeLists line?

**Comment by flint2** [comment]
> Would it work if we prepend `DESTDIR` to the two directory paths? I.e. using `${DESTDIR}${CMAKE_INSTALL_PREFIX}/...` at the two places in that CMakeLists line?

Yes, is working with this change
```
 sed -i 's/ ${CMAKE_INSTALL_PREFIX}/ ${DESTDIR}${CMAKE_INSTALL_PREFIX}/g' "${WORKDIR}"/"${P}"/examples/CMakeLists.txt
```

https://github.com/gentoo/gentoo/compare/d0381b3afc3402218a75aac0b55679b60d2f12f4..cfb0dad0ab48e30ad1e6456768f5092c4d7eb929

**Comment by farindk** [comment]
Thank you, I've added it upstream. Will be part of v1.18.1.

**Comment by eli-schwartz** [comment]
The solution is wrong. :(

You need to look it up at install time, not at configure time. That means that it can't be a cmake variable ${DESTDIR}, it needs to be an environment variable `$ENV{DESTDIR}` which is escaped so that the `install(CODE ...)` evaluates the $ENV{} lookup when running `DESTDIR="/path/to/packaging/destdir" ninja install`

**Comment by farindk** [comment]
> Yes, is working with this change
vs.
> The solution is wrong. :(

Who can resolve this contradiction?

> You need to look it up at install time, not at configure time. That means that it can't be a cmake variable ${DESTDIR}, it needs to be an environment variable `$ENV{DESTDIR}` which is escaped so that the `install(CODE ...)` evaluates the $ENV{} lookup when running `DESTDIR="/path/to/packaging/destdir" ninja install`

But `$ENV` is also evaluated at configure time as far as I know.

**Comment by eli-schwartz** [comment]
> But `$ENV` is also evaluated at configure time as far as I know.

As I said -- you need to escape it.

This evaluates DESTDIR at configure time:
```cmake
install(CODE "
    execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink
        $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/heif-dec${CMAKE_EXECUTABLE_SUFFIX}
        $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/heif-convert${CMAKE_EXECUTABLE_SUFFIX}
    )
")
```

It produces an install rule that executes this code snippet:

```cmake
execute_process(COMMAND /usr/bin/cmake -E create_symlink
    /path/to/packaging/destdir/usr//usr/bin/heif-dec
    /path/to/packaging/destdir/usr//usr/bin/heif-convert
)
```

In comparison, this evaluates DESTDIR at install time, due to the backslash escapes of the dollar symbol:
```cmake
install(CODE "
    execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink
        \$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/heif-dec${CMAKE_EXECUTABLE_SUFFIX}
        \$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/heif-convert${CMAKE_EXECUTABLE_SUFFIX}
    )
")
```
It produces an install rule that executes this code snippet:

```cmake
execute_process(COMMAND /usr/bin/cmake -E create_symlink
    $ENV{DESTDIR}/usr//usr/bin/heif-dec
    $ENV{DESTDIR}/usr//usr/bin/heif-convert
)
```

**Comment by eli-schwartz** [comment]
> > Yes, is working with this change
> > vs.
> > The solution is wrong. :(
> 
> Who can resolve this contradiction?

It "works" in the sense that in combination with passing DESTDIR at configure time -- something that is *never* done by default, and is the kind of thing that linters warn about because one is not supposed to do that at all, ever -- it produces correct results.

It is wrong because:
- it is a stye warning
- it requires people to specify highly unusual configure settings that no one is expecting to set
- it is semantically wrong, because it involves semantics being specified at the wrong level; it is a layering violation.

**Comment by farindk** [comment]
Ok, thanks for the detailed explanation. That makes sense and it works as expected for me.

One thing I'm wondering, though: should we add `${DESTDIR}` also for the link target?
When I'm installing as `DESTDIR=/installdir make install`, we get a link `heif-convert -> /installdir/usr/bin/heif-dec`.

I guess this is not correct and we should remove `${DESTDIR}` from the right hand side, right?

**Comment by eli-schwartz** [comment]
That is correct. Actually, if you think about it, you can remove the prefix/bindir as well -- since the link and its destination are in the same directory, the text of the link (its destination) can just be "heif-doc".

**Comment by farindk** [comment]
Yes, that's even better. I guess that the above commit should be correct now.
