### ISSUE TITLE
hitting unsupported image item for Exif

### ISSUE THREAD

**Issue by bradh** [strukturag/libheif#1337]
As part of the mini box work, I've just rebased, and I think I'm hitting a problem with the new unsupported image item.

The error is:
```
Unsupported feature: Unsupported image type: Image item of type 'Exif' is not supported.
```

The error is coming from `alloc_for_infe_box()` which does not cover the `mime` and `Exif` cases.

I'm pretty sure I'm marking the item as hidden in my code, and it appears to show up with the main branch too.

**Comment by bradh** [comment]
Repro sample

[xmp.avif.zip](https://github.com/user-attachments/files/17373649/xmp.avif.zip)

**Comment by farindk** [comment]
Yes, it appears that the error is triggered because the Exif is not marked as hidden in the file. I will have a closer look at that as I think it should decode anyway as long as the user does not try to decode the Exif as an image item.

When I'm converting with `heif-enc`, the Exif is correctly marked as hidden. How do you write the Exif?

**Comment by bradh** [comment]
It came from avifenc.

However the mini spec requires the flag bit set and I think I am doing that.
