### ISSUE TITLE
incompatible ABI change to enum heif_metadata_compression in 1.18.0+

### ISSUE THREAD

**Issue by rathann** [strukturag/libheif#1387]
Commit ebf6c61260307b0514c134232f79b006a8960b49 swapped the definitions of `heif_metadata_compression_deflate` (2 to 3) and `heif_metadata_compression_unknown` (3 to 2) in [libheif/api/libheif/heif.h](https://github.com/strukturag/libheif/blob/master/libheif/api/libheif/heif.h#L522). This constitutes an ABI break, but there was no corresponding SONAME change.

Any software using the 'unknown' or 'deflate' enums is going to get the meaning of the enums flipped until they are rebuilt against the new version.

Adding new enums at the end of the enumerator list is not a problem, but having 'unknown' and 'deflate' values flipped probably is.

**Comment by rathann** [comment]
Could you put the `deflate` and `unknown` enums back in the previous order?

**Comment by bradh** [comment]
But changing it back again now would be another breaking change, right? So maybe just an SONAME bump.

**Comment by kalev** [comment]
I think I'd just do a quick 1.19.4 or 1.19.3.1 release and mention loudly in the release notes that it is ABI incompatible with broken 1.19.3 release (but compatible with older releases), and just leave it at that. It's only been a few days since 1.19.3 was released and I imagine most distributions have not had time to pick up the new release yet anyway.

As long as there is a big warning to not use 1.19.3, I think this should be a pragmatic solution.

Fedora for example was pondering updating to 1.19.3 and this is where @rathann noticed the enums mixup: https://src.fedoraproject.org/rpms/libheif/pull-request/7. For us, it would certainly be easier if the new release had same soname as 1.18.x - we wouldn't need to rebuild dependent packages then and coordinate rebuilds with rpmfusion, but either way works.

**Comment by farindk** [comment]
Nothing changed between 1.18.0 and 1.19.x. The commit above was between v1.17.0 and v1.18.0 and metadata compression was marked experimental at that time.

Thus, I don't think any action has to be taken.

**Comment by kalev** [comment]
Ahh, sorry, ignore what I said then :)

**Comment by farindk** [comment]
Ignore it. As I said, at v1.17.6, metadata compression was experimental and switched off by default.
Decoders never need that enum and encoders probably still don't use it as I think there is no wide support for metadata compression in anything except libheif anyway.

In current versions of libheif, I put the experimental stuff into `heif_experimental.h`, which is only installed if `ENABLE_EXPERIMENTAL_FEATURES` is enabled in cmake. I hope that this makes it clearer in the future.

**Comment by kalev** [comment]
Sounds good to me - thanks!

**Comment by rathann** [comment]
FWIW, here's the fix for the ABI break in question.
