### ISSUE TITLE
bad thumbnail dimensions for some images

### ISSUE THREAD

**Issue by jcupitt** [strukturag/libheif#211]
Hello again @fancycode,

I think we might have found a problem with thumbnails in HEIC images from some Android phones. This is testing against git master libheif, but v1.5.0 seems to have this too.

For these images, `heif_image_handle_get_width()`/`_height()` correctly reports the thumbnail size as 512x384, but when you decode the image, the size is reported by `heif_image_get_width()`/`_height()` as 512x512. Perhaps it's something to do with thumbnail orientation?

Here's a test program:

```C
/* compile with:
 *
 * 	gcc -g -Wall thumbbug.c `pkg-config libheif --cflags --libs`
 */

#include <stdlib.h>
#include <stdio.h>
#include <libheif/heif.h>

int
main(int argc, char **argv)
{
	struct heif_context *ctx = heif_context_alloc();
	struct heif_error error;
	int n_top;
	heif_item_id *id;
	int i;

	error = heif_context_read_from_file( ctx, argv[1], NULL );
	if( error.code )
		return( -1 );

	n_top = heif_context_get_number_of_top_level_images( ctx );
	printf( "%d top level images\n", n_top );

        id = (heif_item_id *) calloc( n_top, sizeof( heif_item_id ) );
	heif_context_get_list_of_top_level_image_IDs( ctx, id, n_top );

	for( i = 0; i < n_top; i++ ) {
	        struct heif_image_handle *handle;
		heif_item_id thumb_ids[1];
		int n_thumbs;

                error = heif_context_get_image_handle( ctx, id[i], &handle );
                if( error.code ) 
                        return( -1 );

		n_thumbs = heif_image_handle_get_list_of_thumbnail_IDs(
			handle, thumb_ids, 1 );
		printf( "image %d has %d thumbnails\n", i, n_thumbs );

		if( n_thumbs > 0 ) { 
			struct heif_image_handle *thumb_handle;
			struct heif_image *img;

			error = heif_image_handle_get_thumbnail( handle,
				thumb_ids[0], &thumb_handle );
			if( error.code ) 
				return( -1 );

			printf( "  heif_image_handle_get_width(thumb) = %d\n", 
				heif_image_handle_get_width( thumb_handle ) );
			printf( "  heif_image_handle_get_height(thumb) = %d\n", 
				heif_image_handle_get_height( thumb_handle ) );

			error = heif_decode_image( thumb_handle, &img,
				heif_colorspace_RGB, 
				heif_chroma_interleaved_RGB,
				NULL );
			if( error.code ) 
				return( -1 );


			printf( "  heif_image_get_width(thumb) = %d\n", 
				heif_image_get_width( img, 
					heif_channel_interleaved ) );
			printf( "  heif_image_get_height(thumb) = %d\n", 
				heif_image_get_height( img, 
					heif_channel_interleaved ) );
		}
	}

	printf( "success\n" );
	
	return( 0 );
}
```

With this test image:

[20200313_115653.heic.zip](https://github.com/libvips/libvips/files/4329578/20200313_115653.heic.zip)

I see:

```
$ ./a.out ~/pics/heic/20200313_115653.heic
1 top level images
image 0 has 1 thumbnails
  heif_image_handle_get_width(thumb) = 384
  heif_image_handle_get_height(thumb) = 512
  heif_image_get_width(thumb) = 512
  heif_image_get_height(thumb) = 512
success
```

Original bug report for reference https://github.com/libvips/libvips/issues/1574

**Comment by daverupp** [comment]
@fancycode, were you able to have a closer look into this issue mentioned by @jcupitt?

Would be super cool. I am using libvips together with libheif for showing thumbnails of mobile photos. For some android converted heic images, it is not working... with the above mentioned test case from jcupitt you could reproduce it... 

thank you a lot for your effort.
kind regards

**Comment by jpalumickas** [comment]
Hey,

We have same problem with this

**Comment by farindk** [comment]
Sorry for the long delay.
I now had an in-depth look at the test image (thanks, @jcupitt).

That file simply seems the be faulty. It reports an image size of 512x384 in the `ispe` box of the thumbnail, but the actual, compressed image is 512x512, and there is no 'clap' box to crop it to 512x384.

In theory, I could crop it based on the 'ispe' box, but that box is specified as "for information only". Moreover, the thumbnail in the example seems to be right aligned instead of left aligned... 
My guess is that this is simply a bug in the phone's HEIF encoder. That encoder apparently uses hardware to encode 512x512 tiles for the main image and it is apparently reusing the same to encode the thumbnail. But they seem to have forgotten to handle the case where the image has to be cropped.

Hence, in my view, it does not make sense to implement a workaround (especially because of the image being aligned to the right side).

**Comment by jcupitt** [comment]
That's reasonable, thank you for investigating!
