### ISSUE TITLE
RGB<->YUV conversion according matrix_coefficients

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#240]
Hello,
I have a file:
[format_444_matrix0.zip](https://github.com/strukturag/libheif/files/4799551/format_444_matrix0.zip)
which should look like this:
![correct](https://user-images.githubusercontent.com/52529860/85041386-26a25f00-b18a-11ea-9597-66b68c151a1b.png)
but heif-convert created this:
![funny](https://user-images.githubusercontent.com/52529860/85041493-489be180-b18a-11ea-9d48-ac579e9b21cc.png)
format_444_matrix0.avif was created using avifenc using lossless mode (yuv444, maxQ = 0, MatrixCoefficients = 0)

**Comment by farindk** [comment]
Yes, `matrix_coefficients=0` actually means that the image is encoded in RGB instead of YCbCr.
Instead of introducing a special case only for this, I think we need the whole color-profile processing for nclx and ICC in libheif. That's a big to-do item.

I'm not yet sure how to handle this the best way.
Option 1: decoding output is YCbCr image with attached color profile. After decoding, a utility function could convert this to the desired output color space/profile.
Disadvantage: when images include rotation, things get difficult. E.g. when we have 4:2:2 color-spaces.

Option 2: color profiles are handled internally and output is always some RGB. Disadvantage: some 8 bit source image with color profile should probably be better processed in HDR to avoid losing information. But we also don't want to use HDR all the time.

Option 3: decoding output is YCbCr like option 1, but always 4:4:4. Then we can process all transformations, we can compose the images, and we can correctly handle chroma sample positioning. Disadvantage: More processing in YCbCr->RGB conversion.

I currently think that option 3 would give the best trade-off.
Opinions?

**Comment by novomesk** [comment]
Are you aware of the discussion here?
https://github.com/AOMediaCodec/av1-avif/issues/84

**Comment by farindk** [comment]
Thanks for the link. Very interesting. I'll go through it.

**Comment by novomesk** [comment]
I am not sure I understand those 3 options, maybe I am just used to a different terminology.

What I understood from consensus of the AVIF implementers:
ICC profile data are not not used during YUV<->RGB conversion.
`matrix_coefficients` specify how YUV<->RGB should be performed.
Special case is `matrix_coefficients == 12` (Chromaticity-derived) when coefficients are being calculated from selected from `color_primaries`
When opening AVIF, RGB+ICC or RGB+NCLX is the result passed to the user.
I know, many apps know what to do with ICC color profile but many of them doesn't know what to do with enums in NCLX. Color profile defined by NCLX is a combination of `color_primaries` and `transfer_characteristics` (Tone Response Curve) - from them user can create for example via **lcms2**.
This is how I used NCLX in my GIMP plug-in but I do not support all possible TRCs, only those I observed to be used by files I encountered.

I think for some people it would be good to have a helper function which will give them ICC profile instead of NCLX or a helper function which will return `cmsHPROFILE` from NCLX.
It is important that everybody interpret those profiles in same way.

**Comment by novomesk** [comment]
I looked at heif_colorconversion.cc and I have a feeling that RGB<->YUV conversion is always done with coefficients **0.299f, 0.114f** (not absolutely sure, sorry if I am wrong).
Those coefficients **represent matrix_coefficients == 5** (like JPEG)
But AVIF files use different values too, so when other app encode AVIF using MC=1 and libheif assume MC=5, colours will be slightly different.
When MC=2, coefficients are not specified, but I observed that libavif defaults to MC=1 in their code now.

**Comment by farindk** [comment]
The `nclx` profile is now passed into the color conversion pipeline.
YCbCr->RGB can now use the correct matrix coefficients.
There is a hack for `matrix_coefficients=0` in 396ce07, but this is not the final solution. I'm still missing a general way to get the right color conversion coefficients based on the info in `nclx`.

**Comment by novomesk** [comment]
Thank you for this progress!

**Comment by farindk** [comment]
I'm currently reading ITU-T H.273 which covers the color conversion parameters as specified in `nclx`. I think it should be possible to handle this all transparently in the YCbCr->RGB conversion. I will add this in the coming days.

**Comment by farindk** [comment]
The image `Mexico_YUV444.avif`from #237 has this `nclx` box:
````
| | | colour_type: nclx
| | | colour_primaries: 2
| | | transfer_characteristics: 2
| | | matrix_coefficients: 2
| | | full_range_flag: 1
````

However, `matrix_coefficients=2` is specified as "Undefined" everywhere I have looked (HEIF/ISO 23008-12, ISO 14496-12, H.273, not mentioned in AVIF).
Any idea what that means and how it should be handled? I guess it is just an `invalid` input?

**Comment by lclevy** [comment]
Mauve for different white point ? Warm or cold?

**Comment by silverbacknet** [comment]
Just return an error and make the caller request YCbCr so they can convert, or call again overriding the unspecified flag with a specific matrix.

**Comment by novomesk** [comment]
Regarding `matrix_coefficients: 2`
For AVIF with MC==2 (undefined) I suggest to use the same values as MC==1 by default, that's how libavif is doing that.

**Comment by silverbacknet** [comment]
libavif gets it wrong, the entire point of unspecified is that the library shouldn't assume anything, the caller needs to deal with it, either by taking on the conversion externally or by overriding the colorspace flag while calling.

**Comment by silverbacknet** [comment]
And if there's an i_dont_care_just_do_your_thing flag, that's fine, too, I just don't think it should be the default

**Comment by novomesk** [comment]
To have multiple options how to deal MC unspecified(2) is fine for me.
Or to have possibility to set custom values for the coefficients.

**Comment by farindk** [comment]
Thanks for all the feedback. Much appreciated.
Bailing out with an error and putting the burden onto the caller is probably not going to work because nobody will care. I would prefer to simply use a default conversion (as it is doing just now) and attach a warning message to the image that the client can show or let it change the processing. As the client probably also has no idea what to do in this case, I'm not sure whether passing in coefficients to the decoder, just in case, is that useful.

**Comment by farindk** [comment]
I have implemented color conversion coefficients depending on nclx now (except the special cases for matrix_coefficients = 8,11,14). When unspecified, matrix_coefficients=6 is used as a fallback (that are the old coefficients).

full_range=0 is not implemented yet.
