### ISSUE TITLE
AVIF fails to decode with bitdepths

### ISSUE THREAD

**Issue by hackerfactor** [strukturag/libheif#256]
AVIF that is 8bit can only be decoded with RGB, not RRGGBB.
AVIF that is >8bit can only be decoded with RRGGBB, not RGB.

This means decoding needs a conditional. Something like:
  if ((heif_image_handle_get_luma_bits_per_pixel(handle) > 8) ||
      (heif_image_handle_get_chroma_bits_per_pixel(handle) > 8))
    {
    if (EndianHost==BIG_ENDIAN)
      {
      if (has_alpha) { format=heif_chroma_interleaved_RRGGBBAA_BE; }
      else { format=heif_chroma_interleaved_RRGGBB_BE; }
      }
    else
      {
      if (has_alpha) { format=heif_chroma_interleaved_RRGGBBAA_LE; }
      else { format=heif_chroma_interleaved_RRGGBB_LE; }
      }
    }
  else
    {
    if (has_alpha) { format=heif_chroma_interleaved_RGBA; }
    else { format=heif_chroma_interleaved_RGB; }
    } 

With HEIF/HEIC, you can always specify RGB/RGBA, even if the image uses >8bit code.
With AVIF from libaom, the decode format must match the image bit depth (8 or 16 bit).

**Comment by farindk** [comment]
Should be fixed in 87ff646. It was affecting both AVIF and HEIF.

Leaving this open, because I'm not sure yet what the output should be for an 8bit image decoded to RRGGBB.
Currently, this is now up-converted to 10bit. An alternative would be storing 8bit in a 16bit format. But this does not
work currently, as it breaks code in many places.
