### ISSUE TITLE
XMP metadata not found in AVIF

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#269]
[avif_metadata.zip](https://github.com/strukturag/libheif/files/5007027/avif_metadata.zip)
metadata.avif has both EXIF and XMP metadata.
But `heif_image_handle_get_number_of_metadata_blocks (handle, NULL)` returns only 1, just _Exif_ and not XMP.

**Comment by farindk** [comment]
That file is not standard compliant. It contains two `iref` boxes (one for EXIF and one for XMP) while there should be at most one (listing both EXIF and XMP).
Source: ISO 14496-12, ISO BaseMediaFormat Dec/2015

![Screenshot 2020-07-31 14:59:32](https://user-images.githubusercontent.com/968944/89037278-802bab00-d33e-11ea-9125-b2b6d6917f95.png)

Quantity: zero or one

I'd prefer not to add a workaround for this, as it will complicate things while it is in fact a bug in libavif writing this file.

**Comment by novomesk** [comment]
I will write about this to libavif project.

I have another observation regarding the metadata handling in libheif vs libavif.
For example this file from Microsoft: https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Microsoft/Summer_Nature_4k.avif
When I open it via libavif API, Exif metadata have 66 length but in libheif 70 bytes.
There are 4bytes difference, there are four zero bytes before the TIFF header.

When I opened a heic file with metadata, buffer started right at the TIFF header as expected.
I don't know what are those 4 zero bytes before AVIF metadata. Maybe it is an offset. Can you take a look from standard perspective when you have time?

**Comment by farindk** [comment]
The four bytes are an offset to the first byte of the actual EXIF data. I have no idea what the purpose of that offset is, but that's how it is defined in the HEIF standard. The AVIF standard does not say anything about EXIF and XMP, but it seems it is stored just in the same way (libavif references the HEIF standard there).

The difference between libheif and libavif seems to be the convention what to return as metadata. libavif appears to skip the offset internally and only return the data from there on. It doesn't even skip the number of bytes in the offset. It is just thrown away. Contrary to that libheif returns the whole block. I did this, because I thought that the only reason to have an offset can be that there is more data stored in front of the EXIF block. If I would skip that internally, that data would be lost.

**Comment by novomesk** [comment]
Thanks for clarifications!

**Comment by silverbacknet** [comment]
The standard mentions thumbnails and other proprietary junk that can be shoved in from for a vendor-specific EXIF block. It makes sense to send the whole block back, since anytime an image format gets popular, someone's going to abuse all of its obscure features.
