### ISSUE TITLE
Null deref bug in color_profile_nclx::get_nclx_color_profile

### ISSUE THREAD

**Issue by 0xC0000054** [strukturag/libheif#270]
https://github.com/strukturag/libheif/blob/f2abaae290c7927e1818d22be8ce545b6028ff0b/libheif/box.cc#L1642

The code does not check if `malloc` returned NULL before using the allocated data.

Why does this method use a `heif_color_profile_nclx**` signature for the `out_data` parameter?
It seems like it should use `heif_color_profile_nclx*` and populate the structure that the caller passes in.

**Comment by farindk** [comment]
NULL check fixed. But it is intended design to pass the allocated structure back from this function. The reason is that the struct may grow in size in later revisions (see `int version`). In order to be binary backward compatible with new revisions of the library, the struct cannot be allocated by the application.
