### ISSUE TITLE
Limited vs Full range handling

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#273]
[full_and_limited.zip](https://github.com/strukturag/libheif/files/5011816/full_and_limited.zip)
fullrange.avif and limitedrange.avif looks visually same when decoded via libavif.

But when I open them via libheif, there is significant difference in brightness on the limitedrange.avif file.
Can you investigate where is the problem?

I am not a fan of limited range (but some people do), I am just testing various configurations.

**Comment by farindk** [comment]
Yes, I did not implement 'limited range' yet, because I think that's one of the most unuseful things. Just old legacy that should be removed or not used anymore. Its purpose stems back to the old analog TV era, which the sync signals were coded as 'lower than black' voltage levels. Hence, when digitizing those analog TV signals, black was shifted to value 16 to have some space for the sync signals. Nowadays, this is absolutely useless and just reduces the quantizer resolution.

But yes, I'll add this to the decoder just in case anyone is using it. Not sure whether there should be an option of that for encoding. Let that thing die :-)

PS: I'll add it next week. Busy with other things this week.

**Comment by novomesk** [comment]
I don't need limited range during encoding.
Just to load files created by other projects.
No hurry, sometimes I post lot. When I discover something, I share it so we have record of it.
In the future I wish to examine RGB->YUV conversion in various implementations more deeply, to understand differences. I'll share if I find something.

**Comment by farindk** [comment]
The most important color conversions should now cover full_range=0.
