### ISSUE TITLE
Colors distorted when image is converted to AVIF

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#279]
Original image: https://brightrpayments.gumlet.io/wp-content/uploads/2020/03/Acadia_Center_logo.png?original=true

AVIF image: https://brightrpayments.gumlet.io/wp-content/uploads/2020/03/Acadia_Center_logo.png?format=avif

You can check that the AVIF image just shows as black & white in Chrome 85 beta.

**Comment by navanshu** [comment]
The colors are blown and white are too extra, blacks are too dark and it is changing the color space of Images when I used it with Sharp.
I checked the images in chrome beta, edge and even firefox. It is probably because of inaccurate conversion of color space, plus the borders of a round object are getting jagged. The size if also heavy compared to webp and jpeg.

**Comment by adityapatadia** [comment]
@farindk can you take a look at this when you are available?

**Comment by farindk** [comment]
@adityapatadia The logo image has a transparent background. Probably Chrome cannot handle this and displays the alpha map instead of the image. When you convert the AVIF image with `heif-convert`, there is no problem. However, if you convert it to JPEG, the background will look black as JPEG has no transparency information and it is not defined what background color should be used in this case.

**Comment by adityapatadia** [comment]
@farindk Do you say converting with `heif-convert` opens fine in Chrome 85? If so I need to open issue in Sharp library.

**Comment by adityapatadia** [comment]
[ac.avif.zip](https://github.com/strukturag/libheif/files/5062156/ac.avif.zip)
I have created AVIF using `heif-enc` and that file does not open correctly in chrome 85. This is what I see.
<img width="1435" alt="Screenshot 2020-08-12 at 4 16 00 PM" src="https://user-images.githubusercontent.com/1086617/90006749-240a4480-dcb7-11ea-8be7-70c1547a16fb.png">

**Comment by adityapatadia** [comment]
I tried to convert the file to PNG again and that shows fine in Chrome 85 so it's the viewer which creates the problem.

**Comment by farindk** [comment]
Yes, it's a Chroma decoding/display error. As said before, it is apparently showing the alpha plane instead of the color data.

**Comment by adityapatadia** [comment]
Okay thanks for help. The issue is being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=1115483

**Comment by adityapatadia** [comment]
@farindk can you check the chrome issue thread? They say using `avifenc` produces correct image.

**Comment by farindk** [comment]
Copy of my analysis posted in the Chromium bugs thread.
----------------------------------

I have analyzed the box structure in the two images (either generated by libavif and libheif).
They are almost the same. Both save the alpha channel as a separate auxiliary image. Color image has ID 1 while auxiliary image has ID 2.
However, in the iloc box, libavif saves the color image first, while libheif saves the alpha image first. My guess is that Chrome simply takes the image that comes first. However, it should display the primary image, indicated in the pitm box.

I have attached the box structures of the two files.

[libavif.log](https://github.com/strukturag/libheif/files/5068206/libavif.log)
[libheif.log](https://github.com/strukturag/libheif/files/5068207/libheif.log)

**Comment by farindk** [comment]
@adityapatadia Which version of libheif are you actually using to create these images? I have tried with the current master branch of libheif and I don't have this problem. All images show fine in Chrome-beta and decode fine with libavif, including transparency.

I tried to track down the problem in libavif, but it is **not** because of the primary item thing I guessed previously. I also have commented out all the alpha decoding in libavif and the file still displays incorrectly.

However, if I encode the logo images myself with a current libheif, I don't have any problems. I have tested with the aom codec plugin and also with rav1e.

**Comment by farindk** [comment]
@adityapatadia PS: Could also be that this is related to the libaom version you are using during encoding.

**Comment by adityapatadia** [comment]
I am using libaom 2.0 https://aomedia.googlesource.com/aom/+archive/bb35ba9148543f22ba7d8642e4fbd29ae301f5dc.tar.gz

I am using this commit of libheif: https://github.com/strukturag/libheif/archive/c159795676b3123d80ee8ba30bb8cf29b739cf48.zip

**Comment by adityapatadia** [comment]
Let me try with current master.

**Comment by farindk** [comment]
I further tracked it down. The problem only occurs when using libaom as encoder. Images encoded with rav1e display correctly in Chrome-beta and libavif.

**Comment by farindk** [comment]
I made a change in libheif to save the alpha and the color images in different order (first compress color, then alpha). See the commit above. That fixes the problem.

However, I would prefer to first understand the reason why this leads to wrong decoding in libavif/Chrome ... before merging it into the master branch.

**Comment by adityapatadia** [comment]
Unfortunately I am not able to compile rav1e under buster due to this issue: https://github.com/xiph/rav1e/issues/2482

I will wait until you can fix in master branch.

**Comment by adityapatadia** [comment]
<img width="572" alt="Screenshot 2020-08-14 at 12 34 13 AM" src="https://user-images.githubusercontent.com/1086617/90175992-eea04c80-ddc5-11ea-8d96-c05ce01e5257.png">

I am trying to compile rav1e but why do I get the message `AVIF encoder, use local rav1e: no`

**Comment by farindk** [comment]
You have to enable it first. Not sure what tools you use, but for example, I use "ccmake ." (yes, two 'c') to edit the configuration options.

**Comment by adityapatadia** [comment]
`cmake ../ -DUSE_LOCAL_RAV1E=1` hope this will work?

**Comment by adityapatadia** [comment]
This worked but the bug in nasm-rs is now allowing to compile. :(

**Comment by adityapatadia** [comment]
Is it possible to install rav1e via crates? https://crates.io/crates/rav1e/0.3.3. Is it going to make compilation successful?

**Comment by silverbacknet** [comment]
Anything that gets you a .lib you can point to should work, which `crates cinstall` should do.

**Comment by wantehchang** [comment]
I found the bug: aom_encode_image() does not clear encoder->compressedData (a std::vector) before encoding the second image, so the second aom_get_compressed_data() call returns the concatenation of the first and second images.

Note: Aditya reported that heif-convert can decode the second image from the concatenation. I did not investigate why.

Here is a fix:

```
diff --git a/libheif/heif_encoder_aom.cc b/libheif/heif_encoder_aom.cc
index 3169261..87b8933 100644
--- a/libheif/heif_encoder_aom.cc
+++ b/libheif/heif_encoder_aom.cc
@@ -654,6 +654,7 @@ struct heif_error aom_encode_image(void* encoder_raw, const struct heif_image* i
   }
 
 
+  encoder->compressedData.clear();
   const aom_codec_cx_pkt_t* pkt = NULL;
 
   while ((pkt = aom_codec_get_cx_data(&codec, &iter)) != NULL) {
```

**Comment by adityapatadia** [comment]
I used `heif-enc` to convert image and not `heif-convert`

**Comment by wantehchang** [comment]
I wrote a pull request: https://github.com/strukturag/libheif/pull/284

Another potential problem I found, which I don't know how to fix, is in this memset() call in aom_encode_image():

```
  for (int plane = 0; plane < 3; plane++) {
    unsigned char* buf = input_image.planes[plane];
    const int stride = input_image.stride[plane];

    if (chroma == heif_chroma_monochrome && plane != 0) {
      memset(buf, 128, source_height);
      continue;
    }
```

The source_height argument is incorrect. Since that if statement is not executed when I run heif-enc -A, I did not pursue this further.

**Comment by farindk** [comment]
Thanks, @wantehchang . That is great!
Since the problem only occured with the aom encoder, I suspected that it has to do something with not clearing the encoder state correctly. On the other hand, it is very strange that libheif still decoded the two-image pack "correctly".

I'll fix the memset too.

**Comment by adityapatadia** [comment]
Thanks a lot @wantehchang and @farindk 

Now, once you feel it's stable, a release will help a lot :)

**Comment by wantehchang** [comment]
Hi Dirk,

> ..., it is very strange that libheif still decoded the two-image pack "correctly".

I figured that out last night. It has to do with the AV1 decoder used. libheif uses libaom as the AV1 decoder. Since AV1 supports scalable video coding, it is possible to have multiple video frames at one timestamp. These frames belong to different _layers_ and are collected into a _temporal unit_. If a temporal unit has multiple frames in different layers, by default libaom decoder outputs only the last frame in the temporal unit, unless the output-all-layers option is enabled.

The two-image pack actually has two temporal units, but when given to libaom decoder in one shot, I believe (but did not confirm by code inspection or debugging) that libaom treats it as one temporal unit (i.e, libaom does not stop decoding when it encounters the second _temporal delimiter OBU_) and outputs the second image. I confirmed this empirically by changing the Firefox Nightly build to use libaom to decode AVIF. If I do that, then the Firefox Nightly build can display an AVIF image containing the two-pack image correctly.

If you have time for an experiment, you can add this call to libheif/heif_decoder_aom.cc:

```
diff --git a/libheif/heif_decoder_aom.cc b/libheif/heif_decoder_aom.cc
index 6a064a3..2a46126 100644
--- a/libheif/heif_decoder_aom.cc
+++ b/libheif/heif_decoder_aom.cc
@@ -96,6 +96,7 @@ struct heif_error aom_new_decoder(void** dec)
     struct heif_error err = {heif_error_Decoder_plugin_error, heif_suberror_Unspecified, kSuccess};
     return err;
   }
+  aom_codec_control(&decoder->codec, AV1D_SET_OUTPUT_ALL_LAYERS, 1);
 
   *dec = decoder;
 
```

It will make libaom outputs all layers, and libheif will get the first image in the two-image pack.

Chrome. Firefox Nightly build (default configuration), and Microsoft's AV1 Video Extension for Windows 10 all use dav1d as the AV1 decoder for AVIF. I guess dav1d outputs the first video frame in a temporal unit containing multiple layers.

Finally, there is one change that I could not make work last night. I noticed that the AV1 bitstreams encoded by libheif (via libaom) have full_range_flag=0. (Note that I am referring to the _color_range_ flag of the sequence header OBU in AV1 bitstreams, not the full_range_flag in the nclx colr box.)  Ideally we should add something like this to `aom_encode_image()`:

```
  auto colorProfile = image->image->get_color_profile();
  if (auto nclxProfile = std::dynamic_pointer_cast<const heif_color_profile_nclx>(colorProfile)) {
    if (nclxProfile->full_range_flag) {
      // AV1E_SET_COLOR_RANGE default to AOM_CR_STUDIO_RANGE (0).
      aom_codec_control(&codec, AV1E_SET_COLOR_RANGE, AOM_CR_FULL_RANGE);
    }
  }
```

But `image->image->get_color_profile()` returns a null pointer. Do you know what is the right way to get the nclx color profile of the image in `aom_encode_image()`?

Thank you!

**Comment by wantehchang** [comment]
Dirk,

One more thing: for auxiliary images (alpha or depth), I recommend always calling `aom_codec_control(&codec, AV1E_SET_COLOR_RANGE, AOM_CR_FULL_RANGE)`, regardless of the value of full_range_flag in nclx.

**Comment by farindk** [comment]
Thanks @wantehchang for the perfect explanation. Makes perfectly sense. Great.

Also thanks for the note about the full-range flag. You received a null nclx profile because it is currently lost in the color conversion stage. I have opened another issue for that (#288).

**Comment by wantehchang** [comment]
Dirk: Thank you for filing issue #254 

`rav1e_encode_image()` currently uses a hardcoded value of `RA_PIXEL_RANGE_FULL`:

```
struct heif_error rav1e_encode_image(void* encoder_raw, const struct heif_image* image,
                                     heif_image_input_class input_class)
{
  ...
  RaPixelRange rav1eRange;
  ...

  rav1eRange = RA_PIXEL_RANGE_FULL;
  ...

  if (rav1e_config_set_pixel_format(rav1eConfig.get(), (uint8_t) bitDepth, chromaSampling,
                                    RA_CHROMA_SAMPLE_POSITION_UNKNOWN, rav1eRange) < 0) {
    return heif_error_codec_library_error;
  }
```

It should probably use `nclxProfile->full_range_flag` instead.

**Comment by farindk** [comment]
Yes, that has to be changed too.

The whole thing is a bit more complicated, because we also have the case where the color profile is actually an ICC (see #259).
Therefore, I'd like to think about the program structure, before doing quick changes.

**Comment by silverbacknet** [comment]
It might be a long shot, but it might be worth contacting leonardo@chiariglione.org to see if he has any input on ICC profiles, or if he can point you to the person who does. It's not in the standards, so there must be someone who's working on it.

**Comment by 06needhamt** [comment]
There may be a similar issue with AVIF decoding. See https://github.com/ImageMagick/ImageMagick/issues/2415

**Comment by jamesta696** [comment]
I have weird black background on AVIF images on Chrome/FireFox, anyway to fix this? I have used this site to convert WEBP to AVIF ([](https://convertio.co/webp-avif/)) and the black area is supposed to be the transparent (invisible) area.

**FireFox/Chrome:**
![image](https://user-images.githubusercontent.com/14171094/101301515-ec875100-37ed-11eb-9ad6-975c8d4d9c6a.png)

**Comment by silverbacknet** [comment]
@jamesta696 That doesn't seem to have anything to do with libheif. Please contact convertio.co to find out why. You might want to include your input and expected output, since the actual output alone is seemingly fine.

**Comment by farindk** [comment]
@jamesta696 As @silverbacknet said, this is probably either encoded badly or there is a transparency rendering problem. Anyway, I can only have a look at the issue when you attach the encoded AVIF, too.
