### ISSUE TITLE
Unable to decode some heif-enc encoded HEIC files

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#291]
Hello,
I have a 8bit PNG file with transparency. Dimensions are 2001x1984
![8alpha](https://user-images.githubusercontent.com/52529860/90890989-46891580-e3bb-11ea-9224-4426b05cb255.png)
I encode the PNG to HEIC and to AVIF:
```
heif-enc -o failure.heic 8alpha.png
heif-enc -A -o ok.avif 8alpha.png
```
The ok.avif opens fine, but failure.heic returns
`Could not decode image: 0: Unsupported feature: Unsupported color conversion`

I think the problem is related to the image dimensions somehow.

**Comment by farindk** [comment]
Yes, the image has size 2001x1984, but the alpha plane is 2000x1984.
I'll check why the alpha plane has a different size.

**Comment by farindk** [comment]
Problem is that hevc cannot save odd-sized images. Hence, the alpha plane has to be cropped.
This brings up an interesting question: is the auxiliary image cropped before it is attached to the main image or afterwards?
Current problem is that is was cropped twice.

**Comment by farindk** [comment]
The HEIF standard says that an auxiliary image should be treated like a "master image". Not sure what that actually means. I interpret this such that the image transformations for the primary (color) image do not apply to the auxiliary image. We would need separate crop or rotation boxes for the auxiliary images. I think this way makes sense because e.g. depth images may have completely different resolutions.
