### ISSUE TITLE
heif_cxx.h is missing entries for color profile.

### ISSUE THREAD

**Issue by therahedwig** [strukturag/libheif#305]
Hey, I was looking into updating Krita's heif plugin with all the new goodness, and while I can access most functionality, the ability to access the color profile information is missing.

As an aside, does anyone have any idea when to interpret a 10/12 bit image as HDR? For us it makes the difference between whether we should load it as an 16 integer image or a 16 floating point one, but right now the only indication I can find is the presence of maxfall and friends.

**Comment by novomesk** [comment]
I use following code:

scale 10->16bit
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/file-heif.c#L1073

scale 12->16bit
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/file-heif.c#L1086

**Comment by therahedwig** [comment]
> I use following code:
> 
> scale 10->16bit
> https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/file-heif.c#L1073
> 
> scale 12->16bit
> https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/file-heif.c#L1086

yeah, I saw that, and I have no clue what they're basing that on...

**Comment by novomesk** [comment]
You don't understand the constants (1023, 65535) or the recalculation formula? Very similar formula is being used by libavif for example.

**Comment by therahedwig** [comment]
> You don't understand the constants (1023, 65535) or the recalculation formula? Very similar formula is being used by libavif for example.

I do understand them, but my problem is whether something needs to be interpreted as 16bit integer or 16bit float. For both these bit depths, such constants would be the exact same but whether the values should be interpreted as ints or floats makes a huge amount of difference in terms of color management. HDR images as far as I know should be interpreted as floats, but I cannot tell if ALL 10/12 bit images are HDR, because nothing explicitely specifies that. That I read. Because there are a lot of really large specs involved.

**Comment by novomesk** [comment]
I don't know if the data type is mentioned somewhere in specifications.
I believe you can choose data type of your preference because except situation with zero matrix coefficients these values are result of libheif's YUV->RGB conversion.
For example darktable seems to use 32bit float, other apps are using 16bit integers. Simple viewers request data in 8bit precision only.

NCLX profile can indicate use of Perceptual Quantizer (PQ) transfer function or Hybrid Log-Gamma (HLG). I think when profile has BT_2020 or P3 primaries together with PQ or HLG transfer function and output data are in 10 or 12bit precision , we have real HDR.

I don't have support for for PQ/HLG transfer functions in all my apps yet. I will focus on it in the future.

I also wanted to improve Krita's heif plugin to include AVIF support there.
However as I worked on libheif-based plugin for GIMP, I encountered issues in compatibility with other AVIF implementations. Many things are fixed already but some issues are waiting for future release of libheif.
I am waiting for issues in essential features (related to AVIF) to be resolved first prior focusing on more advanced features or other libheif-based apps.
