### ISSUE TITLE
AVIF encoded via cavif-rs

### ISSUE THREAD

**Issue by novomesk** [strukturag/libheif#371]
[cavif-rs.zip](https://github.com/strukturag/libheif/files/5504465/cavif-rs.zip)
Hello,
I received this file from one of the GIMP users, he complained that GIMP cannot open the file.
I get the same error with heif-convert
```
heif-convert UHD-CompressionTest-Leipzig-90-avif.avif output.png
Could not read HEIF/AVIF file: Invalid input: No 'hdlr' box
```

**Comment by farindk** [comment]
The error message is right: there is no 'hdlr' box in this file even though this is required according to the MP4 container specification.
Where does the image come from?

The 'hdlr' contains no crucially important information. It basically tells that the file is an image. But it is still mandatory to be included.

**Comment by silverbacknet** [comment]
I checked cavif-rs (https://github.com/kornelski/cavif-rs) and a search brings up no reference to hdlr, so apparently it's out of spec. There IS useful information in it in case you don't know ahead of time if it's a regular movie file, an image, an audio track, or any of the other wacky variants of MP4 you can have.

Based on https://github.com/image-rs/image/issues/1152#issuecomment-693468943 , the issue's been brought up before regarding imagemagick, and the dev refuses to believe it's required by the spec, just because browser parsers are more lenient.

**Comment by farindk** [comment]
I have made the parsing more forgiving. A missing hdlr is ignored, however when there is a hdlr, it has to be of type "pict".
