### ISSUE TITLE
Issue regarding alpha channel with width bigger than rgb channels width

### ISSUE THREAD

**Issue by jaume-pinyol** [strukturag/libheif#388]
Hi!
I have some heif images generated by an Iphone that the alpha channel has 1 pixel more than the other rgb channels, 
rgb channels have `3690x2674` and the alpha has `3691x2674`. 

This make the code return an Unsupported color conversion error due to this condition:
https://github.com/strukturag/libheif/blob/master/libheif/heif_colorconversion.cc#L3043 
```c
// alpha image should have full image resolution

  if (input->has_channel(heif_channel_Alpha)) {
    if (input->get_width(heif_channel_Alpha) != width ||
        input->get_height(heif_channel_Alpha) != height) {
      return nullptr;
    }
  }
```

The image is fine, I can see it in multiple viewers such as mac viewer, gimp and photoshop. 

After debugging why I was getting the error I got to this line:
https://github.com/strukturag/libheif/blob/master/libheif/heif_context.cc#L1216
```c
      // TODO: check that sizes are the same and that we have an Y channel
      // BUT: is there any indication in the standard that the alpha channel should have the same size?
```
And I've tested forcing the alpha to be restricted to maximum the image size, and libheif processes the image fine.

I still don't know if it's a good idea, checking the standard I did not find any specification about that so I don't know if I should propose a PR (I've already have the code in place) or discard this images and consider them as corrupted image.

Keeping in mind that viewers consider this images as valid probably I'd go with limiting the alpha channel size to the maximum allowed. What do you think?

Thanks for the great work and this awesome library!

**Comment by farindk** [comment]
@jaume-pinyol Thanks for reporting this issue. Could you please attach such an image here as an example? How was the image created? I assume it is a third-party application, as the iPhone camera probably won't attach alpha data.

What is particularly strange is that the alpha image has an odd width, while it is actually much simpler to write an image with even width. Hence, it sounds very much like a bug in the generating software.

My proposal would be: as I will add a way to access arbitrary auxiliary images (see #389), alpha images which do not fit in size to the main color image, will be added as separate aux images.

**Comment by jaume-pinyol** [comment]
Hi, 

Thanks for the info, I'm attaching the file here:
[alpha-bigger-image-size.heic.zip](https://github.com/strukturag/libheif/files/5621859/alpha-bigger-image-size.heic.zip)

Your proposal sounds good!

**Comment by hackerfactor** [comment]
How was alpha-bigger-image-size.heic created?  There's a bunch of weird things in it.

For example:
iinf says that there are 100 items. Item 100 has ID=100 and is of type 'mime'.  
iloc also has 100 items.  It says that item 100 has ID=100, is of type 'mime'. The mime has a specified offset, but the size is zero.
ipma only has 99 items; it doesn't even mention 'mime'.
I thought that ipma needs to have the same number of items, even if an item has zero length.

As you mentioned, the image sizes are wonky:
iinf:infe:grid says Image=1, 3691x2674
The 1st iprp:ipco:ispe says 512x512 (that's fine, it defines grids)
The 2nd iprp:ipco:ispe says 3690x2674 (different width)
The 3rd iprp:ipco:ispe says 512x512 (that's fine, it defines grids)
The 4th iprp:ipco:ispe says 3691x2674 (correct width)

This is the first example that I've seen that has two pictures that are both grids.

I think the actual error in libheif is that it isn't matching the correct ipma properties with the image.
In the ipma block:
  ID=49 says ipco for grid uses 4[ispe 3690x2674] 5[pixi]
  ID=98 says ipco for grid uses 8[ispe 3691x2674] 9[pixi] 10[auxC]
When rendering, libheif see ID=49 but uses the last ispe definition rather than the one defined in the ipma block.

**Comment by Jamaika1** [comment]
Heif photo size problem. When I add matrix coefficients equal to zero, the files are twice as large. I do not know why.
https://github.com/link-u/avif-sample-images/blob/master/hato.png
heifenc -v -b 8 -L -e x265 -p preset=placebo -p chroma=444 -p x265:psy-rd=0 -p x265:ctu=64 input_image -o heif_image
Why can't i convert 16bit png to 8bit heif?

**Comment by farindk** [comment]
@Jamaika1 How is this related to this issue? Please open a new issue for unrelated questions. But short answer: when you set matrix_coefficients=0, you are basically switching of RGB->YCbCr conversion and coding directly in RGB space. Moreover, you might be using chroma 4:4:4 here, while using 4:2:0 with YCbCr.

**Comment by jaume-pinyol** [comment]
@hackerfactor I don't know how it was generated, it was uploaded into the system. The only think I know is that it was taken by an Iphone XS with the back camera.

**Comment by farindk** [comment]
I've changed the code such that alpha images are only combined with the color images when their sizes are equal. When the alpha image has a different size, it can be read as a separate auxiliary image.

@jaume-pinyol Thank you for reporting this and the example image.
