### ISSUE TITLE
heif_image_handle_get_raw_color_profile returns wrong color profile

### ISSUE THREAD

**Issue by hackerfactor** [strukturag/libheif#391]
iOS can generate multiple auxC entries; some are depth maps, others are gain correction, etc.  (See issue #389) Each of these can have their own color profile (colr; ICC Profile).

The functions heif_image_handle_get_raw_color_profile and  heif_image_handle_get_raw_color_profile_size appears to return the last colr (ICC Profile) in the file, and not the one associated with the image (as defined in the ipma record).

In practice with iOS: when there are multiple auxC records, the first colr is the standard iOS color profile, but the auxC records use a different grayscale color profile. heif_image_handle_get_raw_color_profile returns the grayscale profile for the main image rather than the color profile.

**Comment by farindk** [comment]
Could you send me an example picture? The image you sent me for #386 only has one color profile.

**Comment by hackerfactor** [comment]
Example: https://fotoforensics.com/analysis.php?id=8ad6bb968c85d17b422595be536bd473156b6714.2633088&fmt=orig

**Comment by farindk** [comment]
Ok, I have fixed it. The problem was that libheif was assigning the color profiles of the tile images also to the main grid image because early iOS versions did assign the color profile only to the tiles and not the main image. However, it now got confused by the aux images and also assigned the profile of the aux images to the main image.
