### ISSUE TITLE
10bit YUV444

### ISSUE THREAD

**Issue by LoveStep** [strukturag/libheif#40]
Do you any plan add to libheif support > 10-16 bit and 4:4:4 chroma subsampling ?

**Comment by farindk** [comment]
Yes, the h265 decoder already supports this (10-14 bit). Hence, it will not be difficult to add.
Do you know about any software that already supports this?

**Comment by LoveStep** [comment]
Sorry, I do not know any third party software which already supports HEIF YUV444 10bit, but many photo editors already supported PNG48 e.g. PhotoDemon, ArtWeaver, PhotoFiltreHD, ImageMagick, Krita, Gimp, IrfanView, FastStone, FreeVimager, Imagine and lot of specialized programs for working with HDR.

For opening current examples PhotoDemon stable realease recommended.
http://www.mediafire.com/view/t810ou7nx5w1x2a/HDR_420_10bit_1.png
http://www.mediafire.com/view/qi716d0o6p567ib/HDR_420_10bit_2.png
http://www.mediafire.com/view/z1hbey8oso9889y/HDR_420_10bit_3.png
http://www.mediafire.com/view/vo606r7llffdplm/HDR_420_10bit_4.png
http://www.mediafire.com/view/c4a3gtbglstdiqu/HDR_420_10bit_5.png

**Comment by jonsneyers** [comment]
Here is a pull request that adds support for 10 and 12 bit encoding (still only YUV420 though):
https://github.com/strukturag/libheif/pull/86

**Comment by farindk** [comment]
Thanks, Jon, for the pull request. The main blocker for HDR support is currently that the image class does not fully support >8 bit images (color-space conversion, scaling, ...). Maybe we should collect all these changes, together with your PR in a separate 'hdr' branch until all missing parts are ready to be merged into 'master'.

**Comment by jonsneyers** [comment]
We are currently using libheif using YCbCr 4:2:0 image buffers. This works fine for >8 bit (with my PR). We don't use RGB images since the chroma subsampling/upsampling that is currently in libheif is not good enough (and yes, it also only works for 8-bit, but even for 8-bit it is not good enough).

I would say that the image class does not fully support 8-bit images yet, in the sense that the conversion between RGB and YCbCr 4:2:0 is not good enough yet (subsampling just discards 3/4 of the pixels, upsampling does no interpolation). But that's OK, since we can work with the YCbCr 4:2:0 buffers.

You could even do the same thing as libx265, and say that color conversion is not in the scope of the library. The only reason why it would make sense to do the color conversion in libheif, is that HEIF supports layers and these need to be blended in RGBA. Not that I've seen such HEIF files in the wild yet, but still...

For now, I think it would make sense to fully support single-layer YCbCr 4:2:0 first (at 8, 10 and 12 bit), then maybe add 4:4:4 and 4:2:2. That way we can already use libheif, and it doesn't require much implementation effort. Fully supporting multi-layer means you also need to fully support conversion to and from RGBA (which is practical to have anyway even for single-layer, e.g. for the example applications), but that requires more implementation effort to get it right: better subsampling/upsampling, even some color management is needed to get it completely right (since the canvas color is specified in 16-bit sRGB but the image layers that are blended to the canvas might be in another color space).

**Comment by farindk** [comment]
I have added HDR encoding into the 'hdr' branch. Decoding works up to 14 bits/pixel, using libde265. Which bit depths are supported for encoding depends on how your x265 encoder library was compiled. On my system, for example, it can encode with 10 bits and 12 bits.

You can try it out like this:

    heif-enc 10bit-image.png -o output.heic -b 10

You have to specify the output bit-depth because this is not stored in the PNG (HDR PNGs are always 16 bit).

Please give me feedback on any problems with this. After this has been tested for a while, I will merge it into the `master` branch.

**Comment by farindk** [comment]
PS: this is still 4:2:0 only and most of the color conversions are missing.
You are safe using these inputs:
- planar RGB
- planar YCbCr
and these outputs:
- planar RGB
- planar YCbCr
- RRGGBB_BE and RRGGBBAA_BE (big endian)

the interleaved 16bit formats have the values in the high-order bits. I.e. the range is always 0-65535, even for 10bit.

**Comment by fancycode** [comment]
@farindk is this now supported with the latest color conversion improvements?

**Comment by farindk** [comment]
We now also support RRGGBB_LE and RRGGBBAA_LE, to and from basically all other color spaces.
We still have no 4:2:2 and 4:4:4 support, for YCbCr, as I do not see the requirement yet. That would require a matching module in the color conversion framework and also support by the codec plugin.

PS: I just noticed that my remark about the pixel range is not valid anymore (two comments above). The value is in the lower order bits. I.e. 10 bit is 0-1023, not shifted to full 16bit.

**Comment by farindk** [comment]
Closing this old issue. Everything mentioned here has been implemented in the meantime.

**Comment by kharshit753** [comment]
Require YUV444, YUV422, 10-bit .yuv files

**Comment by bradh** [comment]
@kharshit753 this issue is closed. If you have a bug or feature request for libheif you should raise  a new issue with full details.  If you have a question you can raise that in a new discussion topic.
