### ISSUE TITLE
Image quality gets worse when encoding to AVIF (including lossless)

### ISSUE THREAD

**Issue by dooman87** [strukturag/libheif#407]
Hi there,

I'm using `libheif-1.10.0` on Linux with libaom. There is a jpeg example that when I encode loosing sharpness around the edges. I tried both lossy and lossless modes.

Command I was using to encode the original jpeg:

```
./heif-enc -A -o ./asis3.avif ./asis3.jpeg
./heif-enc -L -A -o ./asis3_lossless.avif ./asis3.jpeg
```

I'm attaching original JPEG and AVIFs to the ticket.

**Comment by dooman87** [comment]
Example files:

[asis.zip](https://github.com/strukturag/libheif/files/5732586/asis.zip)

**Comment by novomesk** [comment]
Try to add `-p chroma=444` parameter.

**Comment by dooman87** [comment]
> Try to add `-p chroma=444` parameter.

It's actually became worst and the edges are sharper than before. But thanks for the idea! I will dig more into chroma param.

**Comment by dooman87** [comment]
I tried all the options for `chroma` and with 420 it looks the best, but still very far from original JPEG. I tried to use it with `-L` and the result was the same.

**Comment by Jamaika1** [comment]
You use chroma with 444 for lossless or 420 for lossy. In libheif doesn't change speed/quality effort.
heifenc.exe image_21447_24bit.png -v --lossless -q 100 --avif --no-alpha -p chroma=444 --full_range_flag=1 --enable-two-colr-boxes -o image_21447_24bit.avif
Used encoder with linwebp2 (without alpha)
av1enc.exe -avif -q 100 -444 -size 1563x1558 -effort 5 -thread 4 image_21447_24bit.png -d image_21447_24bitw.avif
or libavif c++17 (cavif,davif)

**Comment by dooman87** [comment]
Thanks @Jamaika1,

I used a command you suggested and there are still artefacts on AVIF image. I put jpeg/avif side by side on HTML page and attaching screenshots here.

Normal scale:
![avif-1x](https://user-images.githubusercontent.com/124110/103713062-7144d500-500f-11eb-807e-641369644176.png)

200% scale on web page:
![avif-2x](https://user-images.githubusercontent.com/124110/103713066-730e9880-500f-11eb-9ef1-f6bac7b0be92.png)

**Comment by Jamaika1** [comment]
See how other converters work. Maybe that's problem aom.
https://www.sendspace.com/file/w32zhs

**Comment by dooman87** [comment]
Thanks for the codecs, but I'm on Linux, so can't try them straight away. I tried [Squoosh](https://squoosh.app) and with lossy compression even on max quality (62) I still can see artefacts. However, artefacts are gone when using lossless compression. I'm wondering if there is any flags I'm missing for lossless compression in `heif_enc`

**Comment by novomesk** [comment]
I think there is a bug in heif-enc utility.

When input is JPG, I see the artifacts when `-p chroma=444` is used.
When input is PNG (converted from original JPG), the result is different. But there is some strange noise in the picture which indicate another problem.

In my build of development GIMP 2.99.5 with libheif 1.10, the output looks OK when YUV444 or RGB is selected. That's why I think the problem is isolated to heif-enc and it is probably not in libheif itself.

**Comment by farindk** [comment]
The reason for this seems to be the upsampling from 4:2:0 to 4:4:4. The upsampling/downsampling filter libjpeg is using is apparently different from the simple box filter libheif is using in the color conversion pipeline. In your example images, you also see a shift of color by ~1 pixel, which is due to the relative position of the chroma samples to the luma samples. In JPEG, the chroma samples for 4:2:0 are located centered between these 4 samples, but in other compression formats, it may be different.

If we want to fix this, we would need a way to specify the chroma sample locations in the input image. However, that is not even the end of the story, because we would also have to specify the chroma upsampling filters to use in the color conversion. Unfortunately, the filters to be used are nowhere specified.

Generally, it's probably not a good idea to use YCbCr, and especially 4:2:0 as input format when trying to achieve lossless compression. When you first convert your image to PNG (so that effectively, libjpeg uses the matching upsampling filter) and then convert that with libheif, everything works fine.

BTW: while investigating this, I found a bug leading to wrong colors when matrix_coefficients=0 is used. This is because the color conversion used the same matrix_coefficients for the YCbCr->RGB conversion as for the final RGB->YCbCr while it should only be used for output.

**Comment by dooman87** [comment]
Thanks a lot for investigating and such detailed explanation @farindk! At least, you found another bug, so it wasn't waste of your time. I'm going to close this one for now. 

You've also mentioned wrong colors and this is something I'm trying to understand/investigate now as well. I'm attaching a test PNG file which when converted to AVIF with lossless option gets slightly different colours. Is it somehow related to a shift you mentioned above? I'm happy to create a separate issue for that one if that's easier.

![test](https://user-images.githubusercontent.com/124110/103948901-ae83a100-518e-11eb-8236-fc398fe8bbfc.png)

**Comment by Jamaika1** [comment]
test image lossless
https://www.sendspace.com/file/2hosqq

**Comment by novomesk** [comment]
I observed that when I use rav1e encoder in heif-enc, the **-L** parameter has no practical effect. The image looks like it was encoded with quality 50 (default?)
-L parameter with AOM encoder works for me.

**Comment by dooman87** [comment]
> test image lossless
> https://www.sendspace.com/file/2hosqq

Thanks @Jamaika1, I was using your command arguments and colors look good now. Thanks!

**Comment by ValZapod** [comment]
> found a bug leading to wrong colors when matrix_coefficients=0 is used.

Actually you broke it with 925c04a. See https://github.com/strukturag/libheif/issues/533.
