### ISSUE TITLE
heif_image_handle_get_depth_image_representation_info has a confusing and unused depth_image_id parameter

### ISSUE THREAD

**Issue by jiawen** [strukturag/libheif#422]
As the title says, the function `heif_image_handle_get_depth_image_representation_info()`, whose comments don't mention the parameters, has `heif_item_id depth_image_id` as its second parameter. At first glance to a newcomer such as myself, it would seem to imply that `handle` refers to the main image handle, and this function would retrieve the metadata associated with one of its attached depth images (identified by `depth_image_id`).

To my surprise, this was not the case. Instead, `depth_image_id` is unused and `handle` is a depth image handle (one of the `heif_image_handle*`s returned by `heif_image_handle_get_depth_image_handle`).

Can we remove the parameter and add some comments? The main objection I see is that this breaks the API.

**Comment by farindk** [comment]
Hi @jiawen . Yes, you are right, there apparently was a bug in the API. I have now changed it such that one should pass the handle of the main image. In order to keep the backwards compatibility, the function now checks whether the input handle is a depth image and also works like before if it is.

Thank you.
