### ISSUE TITLE
Add support for heif_image_handle_get_chroma

### ISSUE THREAD

**Issue by dlemstra** [strukturag/libheif#442]
Would it be possible to add support for `heif_image_handle_get_chroma` (or maybe call it `heif_image_handle_get_image_chroma`?)  so we can use the return value of that method when calling `heif_decode_image`? We are now always using `heif_chroma_420` in the @ImageMagick project but if the image was encoded with `heif_chroma_444` there will be a bit of quality loss.

```c
enum heif_chroma heif_image_handle_get_chroma(const struct heif_image_handle* handle)
{
  return handle->image->get_chroma();
}
```

```c
enum heif_chroma HeifContext::Image::get_chroma() const
{
  heif_item_id id;
  Error err = m_heif_context->get_id_of_non_virtual_child_image(m_id, id);
  if (err) {
    return heif_chroma_undefined;
  }

  return m_heif_context->m_heif_file->get_image_chroma_from_configuration(id);
}
```

**Comment by farindk** [comment]
Recent versions of libheif do all internal processing in RGB. This was required because it has to do the correct YUV->RGB color conversion based on the color matrix stored, and YUV processing leads to all kinds of problems (e.g. a 4:2:2 that is internally rotated by 90 degrees).

YUV output still exists, but just for backwards compatibility. You should ask for an RGB output format. When you ask for YUV, the internal RGB image will be converted back to YUV which is more inefficient.

**Comment by dlemstra** [comment]
Thanks for the tips, we will change this inside ImageMagick.
