### ISSUE TITLE
Error while 'make' attempt on Amazon Linux AMI

### ISSUE THREAD

**Issue by afifda** [strukturag/libheif#473]
As per instruction on Compiling section, I have run ./autogen.sh and ./configure but when I attempted to run make the  compiling process stopped with error 
`In file included from encoder_png.cc:29:0:
/usr/include/libpng12/png.h:2657:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2665:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2673:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
cc1plus: all warnings being treated as errors
make[2]: *** [heif_convert-encoder_png.o] Error 1
make[2]: Leaving directory `/home/ec2-user/imagemagick/libheif/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/imagemagick/libheif'
make: *** [all] Error 2`
I am using:
OS : Amazon Linux AMI - I think Centos family
- I have installed libde256

It's like a C++ runtime causing error, some articles handling error like this with adding the spaces directly to the file, but I think it's not practical since it's a libpng library file.
Is there any suggestion on this issue?
Any help would be appreciated

**Comment by farindk** [comment]
That's a libpng issue. You seem to be using a very old version of libpng (libpng12). A recent version is libpng16.
I had a quick look into the png.h file of libpng16 and cannot find any line similar to the one in your output, so probably the error has already been fixed in libpng.

**Comment by afifda** [comment]
Oh I see. Thanks for the insight. Now the problem is on Amazon Linux/yum distro, I'm not able to find newer version of libpng than libpng12. Let me try installing from the libpng source.

**Comment by hakimscode** [comment]
> Oh I see. Thanks for the insight. Now the problem is on Amazon Linux/yum distro, I'm not able to find newer version of libpng than libpng12. Let me try installing from the libpng source.

hello, were you able to fix this? I also have the same problem and my Linux/yum distro not able to find newer version as well. I'm using amazonlinux:1

**Comment by silverbacknet** [comment]
Amazon Linux isn't designed for building or integrating any new software; its entire purpose is a stable platform that never changes and potentially breaks a legacy application. AL1 is stuck in 2012 (RHEL 6) and EOL even for security updates since a year ago, AL2 is forever stuck in 2017 (RHEL 7). That's how RHEL/CentOS works, and AL is even more stubbornly behind than the actual mainline.

Instead, you should be using Docker images of something less stable on top of them, if you also need the stability for other applications, or else just use a Fedora or Ubuntu AMI from the start.

Amazon has stated that they're going to start offering branded AMIs based around Fedora next year, so you get both the deep integration and the up-to-date packages, but that doesn't help you now.
