### ISSUE TITLE
libheif javafx language binding - structs request

### ISSUE THREAD

**Issue by lanthale** [strukturag/libheif#585]
I am working to create a language binding for Javafx. The problem I am facing is that the important structs heif_image_handle und heif_image are not in C form. That means I cannot access it. 
It would be helpful if there is a C method to return a struct of that type. Because than I can reserve Memory with exactly that structure return from the method and all is fine. 

I tried to get the information from api_structs.h but I could not find out how image_handle and image is structured without CPP data formats.

**Comment by farindk** [comment]
These structs are hidden on purpose. I intentionally hide them from the public API so that these structs can be changed (e.g. enlarged) when updating the library without breaking API backward compatibility.

I the (current) size was public and you would allocate that memory from outside, the library would never again be able to extend the struct. Furthermore, you probably would have awkward dependencies, e.g. on the C++ compiler or C++ std-library used, as each could have a different std::shared_ptr<> implementation.

Thus, handle these pointer as opaque pointers without doing any assumptions on the data they are pointing to.
