### ISSUE TITLE
How can I get the bitstream into RGBA data?

### ISSUE THREAD

**Issue by jassonjackson** [strukturag/libheif#6]
hi,I get bitstream through the nokiatech/heif library. How do I turn bitstream into rgba data?thank you！

**Comment by farindk** [comment]
Hi, if you are using libheif for still images, there is probably no reason to use the nokiatech/heif library. It is much simpler to decode directly with libheif, because there are additional steps to do (image tiling, transformations, combining with alpha channels, ...).

If you really want to get pixel data from the HEVC bitstream, you might have a look at libde265, which is the hevc decoder. A description how to use the decoder is here: https://github.com/strukturag/libde265/wiki/Decoder-API-Tutorial
