### ISSUE TITLE
box.cc incompatible integer type errors when trying to compile

### ISSUE THREAD

**Issue by kshepherd2013** [strukturag/libheif#617]
There are several lines like this, in box.cc:
**uint32_t** num
...
assert(num <= std::numeric_limits<**int32_t**>::max());
where a uint32_t is compared to std::numeric_limits<int32_t>::max() in an assert.
The compiler flags are set to report this as an error, and abort.
The fix is to replace **int32_t** with **uint32_t** in the assert line.
They occur on line 64 and 65 and  2334 thru 2341.
I have tested this and it works, I can compile, install and convert AVIF files.

**Comment by farindk** [comment]
Should be fixed in ba1547b.
We cannot change the numeric_limits type to uin32_t, because its purpose is to check that it fits into the int32_t range.
However, the limit value should be cast to uint32_t. I have changed this accordingly.
If the issue still occurs, please reopen and paste the compiler error message.
