### ISSUE TITLE
Question. How to check what codec was used

### ISSUE THREAD

**Issue by o-alexandrov** [strukturag/libheif#700]
Sorry for raising a question here; however, this may lead to an opportunity to improve `readme.md`.

## Problem

When compiling from source: `libaom` and then `libheif`, `libheif` shows it found `libaom` during `configure` step:
```sh
checking pkg-config is at least version 0.9.0... yes
checking for aom... yes
checking aom/aom_decoder.h usability... yes
checking aom/aom_decoder.h presence... yes
checking for aom/aom_decoder.h... yes
checking aom/aom_encoder.h usability... yes
checking aom/aom_encoder.h presence... yes
checking for aom/aom_encoder.h... yes
```

However, when printing variables, `libheif` doesn't indicate `libaom` is configured:
```sh
$ pkg-config libheif --print-variables
builtin_avif_encoder
exec_prefix
builtin_h265_encoder
prefix
libdir
includedir
builtin_avif_decoder
builtin_h265_decoder
```

## Question

Is, not showing `libaom` in variables, the expected behavior?
- if it is, then what's the proper way to check what codec would be used for encoding/decoding from the CLI?

**Comment by farindk** [comment]
For encoding, the encoders are listed with `heif-enc --list-encoders`. For AVIF, use `heif-enc -A --list-encoders'. The top entry is used by default.
For decoding, I'll add a similar option.

Converning the `pkg-config` output, I think we cannot tell the available codecs anymore, because I just introduced a plugin system where the codecs can be loaded dynamically. The only thing that might be possible is to list when codecs are built-in to libheif itself. However, it is not clear how useful that would be.

**Comment by o-alexandrov** [comment]
@farindk Thank you very much. [This PR](https://github.com/strukturag/libheif/pull/701) is based on your comment
