### ISSUE TITLE
Error in make 

### ISSUE THREAD

**Issue by antoweb** [strukturag/libheif#716]
successfully compiled libde but compiling libheif got an error:

ological-compare -o .libs/heif-info heif_info-heif_info.o  ../libheif/.libs/libheif.so -lpthread
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_full_range_flag'
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_transfer_characteristics'
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_colour_primaries'
/usr/bin/ld: ../libheif/.libs/libheif.so: undefined reference to `de265_get_image_matrix_coefficients'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:668: heif-info] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by farindk** [comment]
Seems to be an old version of libde265. You need at least libde265 v1.0.7.

**Comment by antoweb** [comment]
I have 1.0.9

**Comment by antoweb** [comment]
Thanks solved removing old version from apt

**Comment by farindk** [comment]
Thanks for the feedback.

**Comment by silverbacknet** [comment]
> Seems to be an old version of libde265. You need at least libde265 v1.0.7.

In that case the test should probably be `if (LIBDE265_VERSION VERSION_GREATER_EQUAL "1.0.7")` instead of `if (LIBDE265_FOUND)`

I'm not sure how to tell pkgcheck/find_library upfront to look harder if it finds the wrong version, though.

**Comment by farindk** [comment]
There is already a check against 1.0.7 in the code:
https://github.com/strukturag/libheif/blob/e5672d30b26e3c7d5caad259fcd502f3b1a104a9/libheif/plugins/heif_decoder_libde265.cc#L344

The problem is usually that on broken installations, it takes the header file from the manually installed source, but the linker library is taken from the old system installation.
I'm not sure whether it's possible to check the library version during linking. But all it could do is to tell the user that the library binary does not match the header file.
