### ISSUE TITLE
Investigate fuzzing errors from #64

### ISSUE THREAD

**Issue by fancycode** [strukturag/libheif#72]
In #64 the CI fuzzer found two potential errors:
https://travis-ci.org/strukturag/libheif/jobs/418152399
https://travis-ci.org/strukturag/libheif/jobs/418152401

Please investigate if this is still an error or was already fixed in master.

**Comment by farindk** [comment]
Just from looking at the source, I have no idea, how this can happen.

In order to save a `colr` box, `set_color_profile` has to be called. The only place this could be done is in `heif_context.cc:1580`, but only if there is a color profile set in the input image (see line 1565), which it is not by default (`shared_ptr` should be initialized to `nullptr`).

Can the fuzzer input data be reproduced?

**Comment by fancycode** [comment]
Yes, the fuzzer logs a line

> INFO: Seed: 4029282012

which can be used to run with the same permutations:
`./path/to/fuzzer -seed=4029282012`

**Comment by farindk** [comment]
Found it. The travis was run before this commit, which fixed it: 472d9e2e9d83bcd3a06f108139d6056918c0df9e

**Comment by fancycode** [comment]
Thanks!
