### ISSUE TITLE
plugin on Windows

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#731]
dlopen --> LoadLibrary
dlclose --> FreeLibrary
dlsym --> GetProcAddress

see
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya
and
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress

it should be easy to write a class to embed this for linux and Windows

**Comment by vtorri** [comment]
and you add a completely useless big dependency... Honestly, the calls are almost exactly the same, no difference except the fct names and the types.

**Comment by farindk** [comment]
The implementation is probably easy enough that we can add the system-specific implementation for Windows without adding any dependencies.
libltdl would have the advantage to support even more systems, but HP-UX and BeOS are probably not that significant anymore.
libltdl mentions NSAddImage for macOS, but that seems to be deprecated and should be replaced with dlopen anyway.
I.e. we just need a Windows implementation for now.

**Comment by kmilos** [comment]
For Glib I agree, but libltdl is not that big... In any case, sure, it's simple enough to be done directly if its only Windows. There's even the https://github.com/dlfcn-win32/dlfcn-win32 under MIT license that can be leveraged. It's already packaged for MSYS2 (MinGW) and also available through vcpkg (MSVC). Or just use the source directly, like it's already being done for `getopt`...

Looks like there is a bit more involved in order to properly handle path/separator differences for MSVC/MinGW/Cygwin, errors, etc.

**Comment by farindk** [comment]
@kmilos Thanks, dlfcn-win32 is also a good proposal.

**Comment by vtorri** [comment]
for path separator, \ and / are supported with the win32 API and win32 crt. Also, for the libheif plugin system, i doubt that there will be a lot of problems with path.

**Comment by farindk** [comment]
Implemented with 38ea1ba75c7022318596c1be5bc289f0195a2bfd
