### ISSUE TITLE
License for the Go bindings?

### ISSUE THREAD

**Issue by mholt** [strukturag/libheif#789]
Hi,

I've been happy to see there is an official Go package now. However, I find the licensing a bit confusing because https://github.com/strukturag/libheif/blob/master/go/heif/heif.go contains the GPL header, even though libheif is distributed under LGPL, from what I can deduce from https://github.com/strukturag/libheif/issues/778. I also saw in other issues that sometimes there were just copy-paste errors for the licensing, that were fixed.

Was it intentional to put the GPL header in heif.go? Is it actually LGPL?

Thanks!
-Matt

**Comment by farindk** [comment]
Right, that was somehow the wrong header. Thanks for letting me know.

**Comment by mholt** [comment]
Awesome, thanks for clarifying! :smiley:

**Comment by jerbob92** [comment]
@farindk would you consider releasing the Go bindings under a more open license since in Go you don't really talk about static or dynamic linking, GPL/LGPL don't make a lot of sense in that case, and it makes it hard to comply with that license if you want to distribute it as part of something that then dynamically invokes libheif through Go.

**Comment by farindk** [comment]
I do not know much about Go, but changing the wrapper license alone will not make a difference when the library itself is still LGPL, right?

To comply with the LGPL, I believe it is allowed to distribute a statically linked executable as long as also the `.o` of the software is distributed that can be linked with the `.o` of libheif by the user.

I also found this [stackoverflow question](https://stackoverflow.com/questions/19431296/building-and-linking-dynamically-from-a-go-binary) that actually says that Go 1.5 can do dynamic linking. Maybe some changes are required in the Go wrapper to support this. I am missing the Go experience to judge this.

**Comment by jerbob92** [comment]
> I do not know much about Go, but changing the wrapper license alone will not make a difference when the library itself is still LGPL, right?

The library itself is called through the wrapper, which is done through dynamic linking (it calls the methods in the libheif .so files through CGO), which works for LGPL, since you can just replace the libheif so file with something that is compatible. 

> To comply with the LGPL, I believe it is allowed to distribute a statically linked executable as long as also the .o of the software is distributed that can be linked with the .o of libheif by the user.
>
> I also found this [stackoverflow question](https://stackoverflow.com/questions/19431296/building-and-linking-dynamically-from-a-go-binary) that actually says that Go 1.5 can do dynamic linking. Maybe some changes are required in the Go wrapper to support this. I am missing the Go experience to judge this.

While technically it is possible to do dynamic linking with Go, it's really uncommon. I think this is only used when you want to write something in Go and then call that from a C program. If you just want to build a Go binary that you can run somewhere, it uses static linking, which doesn't comply with the LGPL. Since this wrapper is basically just a gateway to libheif, and probably doesn't really contain anything IP sensitive, I thought you might were open to make use of a more open license for just the wrapper.

**Comment by jerbob92** [comment]
That is correct indeed. MIT would be perfect!

**Comment by farindk** [comment]
@fancycode Are you ok with changing the license of the Go wrapper to MIT? I believe so since you also proposed that last year, but I wanted to be sure before I do the change.

**Comment by fancycode** [comment]
MIT is fine with me.

Please note that I started moving the Go bindings to a separate repository so they can be developed independently:
https://github.com/strukturag/libheif-go

I'll update the license there, too.
