### ISSUE TITLE
pass private surface data to heif decoder

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#842]
Currently, I use libheif like that : 

 * I get my private surface data, named for example `data`
 * I get the heif `plane` with heif_image_get_plane_readonly()
 * i do a double for loop to copy the values of `plane` to my private surface `data`

is it possible to pass my private `data` to heif decoder so that it fills it directly, without doing the extra loops ?

**Comment by vtorri** [comment]
the surface has a different colorspace : we have BGRA (B == lowest byte and A == highest byte), while libheif is RGBA (R == lowest byte and A highest byte)

maybe you know how do do this conversion with just a memcpy. I don't know how to do that.

if you add our colorspace, then it would be simpler. Our surface support stride, btw.

**Comment by farindk** [comment]
When you have a different color ordering, you'll have to transpose this anyway. Thus, passing a buffer into libheif will not make much of a difference. Instead of doing byte-by-byte copies, you could use a SIMD instruction like PSHUFB (https://www.felixcloutier.com/x86/pshufb.html) to reorder many bytes (up to 64 bytes for AVX512) in one instruction.

Adding another colorspace to libheif may be a future option, but color-conversion should not be the focus of libheif.

**Comment by vtorri** [comment]
@farindk can you tell me where to look in the code if i want to add heif_chroma_interleaved_BGRA colorspace ?

**Comment by farindk** [comment]
`libheif/color-conversion`. But I would not recommend this. Do the conversion on your side and then pass a supported RGB colorspace into libheif.

**Comment by farindk** [comment]
But that won't be faster. Do the conversion outside and write the conversion output directly into the libheif image. There is no faster way.
