### ISSUE TITLE
Licensing paradox

### ISSUE THREAD

**Issue by ItalyPaleAle** [strukturag/libheif#87]
I find it a bit unusual that the libraryitself is released under LGPL, while the sample code is under GPL. Usually, projects have the same license for the sample code as they have for the library itself, if not something more permissive.

The fact that the samples are under GPL puts users in the weird situation where we can’t look at the sample code (whose purpose is to.... well, be a sample) in our applications, unless they get GPL’d too. Combine this with the fact that libheif’s documentation is essentially inexistent (unless i just didn’t look deeply enough), and it makes using the library very complicated.

Is there a reason for this unusual licensing choice?

(I’d like to use libheif for a personal project that will be open sourced)

**Comment by farindk** [comment]
I don't see any issue here. The only difference between LGPL and GPL is that LGPL additionally allows you to link the library to proprietary code. Since you are not going to link the sample code (which is no library), what would be the use of LGPL?

You are welcome to look at all the sample code and copy-paste parts from it.

**Comment by ItalyPaleAle** [comment]
Hi @farindk. Thanks for answering!

I’m afraid that’s not really how the GPL works. If I copy-paste snippets of GPL code into my app, then I need to release my entire app under GPL.

You might read more here: https://lukasa.co.uk/2012/05/GPL_vs_MIT_Which_License_To_Use/

Just to be clear, my issue isn’t with you choosing GPL, LGPL or any other license. The issue is with the fact that by LGPL’ing the library, you’re telling me it’s ok to use it in projects that aren’t GPL’d. But by GPL’ing the samples, you’re telling me that I can’t look at the sample code (which is the only “documentation” so far) unless my code becomes GPL’d too.

**Comment by farindk** [comment]
Well, if you copy snippets from the API samples, I would consider that fair use, and I can assure you that I won't sue you for that :-)

However, to make things clearer, I'll check whether we can use the MIT license for the samples. LGPL does not help because you still would not be allowed to copy from there to proprietary code. LGPL just allows linking to it.

**Comment by farindk** [comment]
Changed license for all example programs to MIT.

**Comment by ItalyPaleAle** [comment]
Thank you!
