### ISSUE TITLE
Are non-grayscale aux images possible(exists somewhere in a wild)?

### ISSUE THREAD

**Issue by bigcat88** [strukturag/libheif#926]
Question: Does currently most AUX images are in grayscale format or not?

If anyone have non grayscale aux images I will be very appreciated to see such images.

**Comment by bradh** [comment]
Meta comment: could the project enable Q&A functionality? There are a few issues that aren't really libheif bugs...

**Comment by farindk** [comment]
Auxiliary images can be any format even though I haven't seen any auxiliary images that are intentionally colored.

To be more specific: alpha and depth auxiliary images should be interpreted as greyscale, but they may be stored as color images, in which case the color planes are ignored. If fact, old versions of libheif did this, and still does, when an encoder  does not support monochrome encoding (rav1e).

Concerning your comment in the pillow_heif issue: I think we need a way to get the internally stored color format so that you don't have to guess this.

PS: I've enabled discussions.

**Comment by bigcat88** [comment]
Thanks for reply and thanks for enabling discussions.

**Comment by farindk** [comment]
PS: I have just added a function `heif_image_handle_get_preferred_decoding_colorspace()`. Does that fit your need in getting the input image colorspace before decoding?
BTW: The information obtained from this is now also written with `heif-info`.

**Comment by bigcat88** [comment]
the name looks like that yeah, it is what I am waiting for. Did no see a commit with it to test...

**Comment by bigcat88** [comment]
Yeah, looks like what is needed, big thanks for adding this.
