### ISSUE TITLE
QUESTION: is frame-parallel branch of libdbe265 still preferred?

### ISSUE THREAD

**Issue by graymouser** [strukturag/libheif#94]
Hi, thanks so much for your great work on this, it's really useful!
I have a question, I see that in the compiling guide for this project it recommends the frame-parallel branch of libde265, but I see that branch is now somewhat older than master.
Is it still recommended to use the frame-parallel branch or should we be using master?
Thank you!

**Comment by farindk** [comment]
The `frame-parallel` branch is decoding faster than the `master` branch, but you probably won't see a difference for the HEIF use case (single images).
The reason both branches are still separate is that the 'frame-parallel' branch required some changes to the API and I still do not yet consider this API stable. Since changing APIs is a big problem for packaging, it is currently still better to use the older `master` branch.

**Comment by graymouser** [comment]
Thank you for your informative answer!
