### ISSUE TITLE
Use dav1d instead of libaom for AVIF support

### ISSUE THREAD

**Issue by ngaurav** [strukturag/libheif#96]
Dav1d is a better decoder for AV1 video stream than compared to libaom. Their goal is to release their first version which fully supports all AV1 specs by the end of 2018. Yesterday they published a commit with heading - "on road to 0.1.0" They have completed all the milestones for their first released. The release may happen any time now. Here is their repository:
[https://code.videolan.org/videolan/dav1d](https://code.videolan.org/videolan/dav1d)
And here are their test results:
https://docs.google.com/spreadsheets/d/1AO3lDZnpC8pNJffOknY1rIxXwLog_ISwHhO_sv3Xlhg/edit#gid=923904571

**Comment by ngaurav** [comment]
They released 0.1.0 "Gazelle"

**Comment by farindk** [comment]
I am currently using 'libaom' because we need both an encoder and a decoder. Furthermore, there is a Debian package for 'libaom' while there is non yet for 'dav1d' (as far as I know).
Once that code is stable, is packaged, and has clear advantages, we will add support in libheif. It's quite easy, as we simply have to add a decoder plugin for it.

**Comment by cryptomilk** [comment]
Either use dav1d for decoding and rav1e for encoding or use https://github.com/AOMediaCodec/libavif/

**Comment by brad0** [comment]
I see there is support for rav1e now as an encoder. Please add dav1d support for the decoder. I see molasses slow Debian finally has a package.

**Comment by brad0** [comment]
This can be closed since there has been dav1d support for awhile.
