### ISSUE TITLE
Fix Emscripten CI tests

### ISSUE THREAD

**Issue by fancycode** [strukturag/libheif#977]
#925 broke the Emscripten CI, so adding an issue to bring back testing of Emscripten.

_Originally posted by @fancycode in https://github.com/strukturag/libheif/issues/925#issuecomment-1752742429_

**Comment by farindk** [comment]
Yes, I tried to fix the emscripten thing a couple of days ago, but I failed to understand what is going on in the code. It would be nice if you could have a look.

**Comment by jerbob92** [comment]
I believe the JS test might not be correct. The functions are not directly available after the import (afaik), so in this code:
```
    var libheif = require('../libheif.js');
    console.log("Loaded libheif.js", libheif.heif_get_version());
```

I don't think `heif_get_version` is defined directly afterwards. It could be that was the case with an older version of Emscripten. 

This is also why https://github.com/strukturag/libheif/blob/master/examples/demo.html runs on `window.onload`.

**Comment by jerbob92** [comment]
In that case, probably. I only looked at the example.html, and that still worked, didn't know there was a unit test.

Not completely sure if it can be fixed in Emscripten, I think they intentionally changed it to work this way. 

Perhaps we should look at how it currently wraps the generated JS too, it does some magic which shouldn't really be necessary anyway: https://github.com/strukturag/libheif/blob/master/pre.js#L35 and https://github.com/strukturag/libheif/blob/master/post.js

**Comment by jerbob92** [comment]
Reading [this](https://emscripten.org/docs/compiling/WebAssembly.html) following page it seems that `WASM_ASYNC_COMPILATION=0` would fix it, but it comes with some sidenotes: `but that may not work in Chrome due to current limitations there.`.
